package FEApp;


/**
* FEApp/FEMethod.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/vanduong/Desktop/Concordia University/Courses/Distributed Systems/workspace/DistributedSystemProject/src/FEidl.idl
* Wednesday, August 7, 2019 10:11:46 PM EDT
*/

public interface FEMethod extends FEMethodOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FEMethod
