package FEApp;


/**
* FEApp/FEMethodHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/vanduong/Desktop/Concordia University/Courses/Distributed Systems/workspace/DistributedSystemProject/src/FEidl.idl
* Wednesday, August 7, 2019 10:11:46 PM EDT
*/

abstract public class FEMethodHelper
{
  private static String  _id = "IDL:FEApp/FEMethod:1.0";

  public static void insert (org.omg.CORBA.Any a, FEApp.FEMethod that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FEApp.FEMethod extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FEApp.FEMethodHelper.id (), "FEMethod");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FEApp.FEMethod read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FEMethodStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FEApp.FEMethod value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static FEApp.FEMethod narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FEApp.FEMethod)
      return (FEApp.FEMethod)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FEApp._FEMethodStub stub = new FEApp._FEMethodStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static FEApp.FEMethod unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FEApp.FEMethod)
      return (FEApp.FEMethod)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FEApp._FEMethodStub stub = new FEApp._FEMethodStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
