package FEApp;

/**
* FEApp/FEMethodHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/vanduong/Desktop/Concordia University/Courses/Distributed Systems/workspace/DistributedSystemProject/src/FEidl.idl
* Wednesday, August 7, 2019 10:11:46 PM EDT
*/

public final class FEMethodHolder implements org.omg.CORBA.portable.Streamable
{
  public FEApp.FEMethod value = null;

  public FEMethodHolder ()
  {
  }

  public FEMethodHolder (FEApp.FEMethod initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FEApp.FEMethodHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FEApp.FEMethodHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FEApp.FEMethodHelper.type ();
  }

}
